### ISSUE TITLE
Null pointer exception on success of enqueue()

### ISSUE THREAD

**Issue by amit3vedi** [Authing/authing-java-sdk#18]
i'm using JAVA sdk of Authing (3.0.1) and if i try to use `enqueue()` to call API asynchronously on success response i'm getting `KotlinNullPointerException` i think it's because of the use of `!!` with `size` because `errors` will always be null on success in this line `if (graphQLResponse.errors?.size!! > 0) {` of `GraphQLCall.kt`

**Comment by andyzhaozhao** [comment]
We have fixed this bug in 3.0.3 . Thank you very much for your feedback.
