### ISSUE TITLE
autoRegister=false param has no effect in loginByPhoneCode() method

### ISSUE THREAD

**Issue by amit3vedi** [Authing/authing-java-sdk#20]
if user is not registered and try to do `loginByPhoneCode`  it automatically registers user and user can login without registration. to prevent that i also tried passing `autoRegister=false` still behavior is same

**Comment by luojielin** [comment]
You can use this method, It's supported.
`authenticationClient.loginByPhoneCode(new LoginByPhoneCodeInput(phone, phoneCode,false)).execute();`
