### ISSUE TITLE
优化BaseClient

### ISSUE THREAD

**Issue by ximplez** [Authing/authing-java-sdk#21]
BaseClient中创建http请求中，设置header的token字段使用的是client的属性token进行赋值，这大大降低了BaseClient的通用性，如果能把token字段在BaseClient的创建请求中设置为从参数获取，这样可以通过继承BaseClient做更多的扩展，而且也不用每个请求都创建一个client对象吧，只需要传入token即可。
个人意见，希望探讨一下可行性，感谢~

**Comment by luojielin** [comment]
您好，ManagementClient 只需要创建一次，复用即可。
您也可以直接通过 setToken 方法来传入 token 
`managementClient.setToken(token);`
