### ISSUE TITLE
查看用户操作日志缺少appIds删除

### ISSUE THREAD

**Issue by wangsuiche** [Authing/authing-java-sdk#23]
https://docs.authing.cn/v2/reference/sdk-for-node/management/StatisticsManagementClient.html 
javascript的**查看用户操作日志**含有参数
options.appIds <string[]> 应用 id ， 可选值

java版本的能否也加一下

**Comment by luojielin** [comment]
您好，在新版本的 SDK 中重新设计了查看用户操作日志接口，支持了 appId 参数。
