### ISSUE TITLE
绑定社会化登录

### ISSUE THREAD

**Issue by leinue** [Authing/authing-java-sdk#8]
https://docs.authing.cn/authing/sdk/authing-sdk-for-web/bind-social-accounts

**Comment by HowieWolf** [comment]
读取绑定列表永远无数据，我绑定成功，然后查询，仍然没有数据

**Comment by leinue** [comment]
> 读取绑定列表永远无数据，我绑定成功，然后查询，仍然没有数据

应该是参数传错了？绑定时候传的 userInfo 是 oauth 的 userInfo，不是 authing 的 userInfo

**Comment by HowieWolf** [comment]
明白。但是 userInfo 说到底不就是一个 string 吗？你服务端会解析和验证？
再者说，如果我 userInfo 传错了，那不应该是绑定失败吗？为什么绑定返回的结果是正确的？

**Comment by leinue** [comment]
> 明白。但是 userInfo 说到底不就是一个 string 吗？你服务端会解析和验证？
> 再者说，如果我 userInfo 传错了，那不应该是绑定失败吗？为什么绑定返回的结果是正确的？

是 string，那可能是有 bug，你能保留参数吗？我让开发这块的同学测试一下

**Comment by leinue** [comment]
#12
