### ISSUE TITLE
自定义请求链接

### ISSUE THREAD

**Issue by leinue** [Authing/authing-java-sdk#9]
https://docs.authing.cn/authing/sdk/authing-sdk-for-web/zi-ding-yi-qing-qiu-lian-jie

**Comment by HowieWolf** [comment]
这个自定义请求连接，就是客户端保存即可吧？

**Comment by leinue** [comment]
> 这个自定义请求连接，就是客户端保存即可吧？

是的

**Comment by leinue** [comment]
#12
